//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LNTSlipPortal_Repository.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Document
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Document()
        {
            this.RAWS = new HashSet<RAW>();
        }
    
        public int DocumentId { get; set; }
        public Nullable<bool> BOM { get; set; }
        public string BOMRevision { get; set; }
        public string BOMCatNo { get; set; }
        public Nullable<bool> AssemblyList { get; set; }
        public string AssemblyListRevision { get; set; }
        public string AssemblyListCatNo { get; set; }
        public Nullable<bool> GeneralAssembly { get; set; }
        public string GeneralAssemblyRevision { get; set; }
        public string GeneralAssemblyCatNo { get; set; }
        public Nullable<bool> TestingDocument { get; set; }
        public string TestingDocumentRevision { get; set; }
        public string TestingDocumentCatNo { get; set; }
        public Nullable<bool> WiringScheme { get; set; }
        public string WiringSchemeRevision { get; set; }
        public string WiringSchemeCatNo { get; set; }
        public Nullable<bool> ProductData { get; set; }
        public string ProductDataRevision { get; set; }
        public string ProductDataCatNo { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RAW> RAWS { get; set; }
    }
}
