//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LNTSlipPortal_Repository.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class RAW
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public RAW()
        {
            this.StatusLogs = new HashSet<StatusLog>();
        }
    
        public int RAWSID { get; set; }
        public Nullable<int> ProjectId { get; set; }
        public string RAWSNO { get; set; }
        public Nullable<int> ProductCatId { get; set; }
        public string ProductDescription { get; set; }
        public string AdditionalWork { get; set; }
        public Nullable<int> TotalQuantity { get; set; }
        public Nullable<int> ScopeId { get; set; }
        public Nullable<int> TotalManHours { get; set; }
        public Nullable<int> ActualManHours { get; set; }
        public Nullable<int> ScopeOfWorkId { get; set; }
        public Nullable<bool> JigFixtures_SpecialTools { get; set; }
        public string JigFixtures_Detail { get; set; }
        public Nullable<int> DocumentId { get; set; }
        public System.DateTime CreatedAt { get; set; }
        public int CreatedBy { get; set; }
        public bool IsActive { get; set; }
        public string Work { get; set; }
        public int Status { get; set; }
        public Nullable<long> NCRNo { get; set; }
    
        public virtual Document Document { get; set; }
        public virtual ProductCategory ProductCategory { get; set; }
        public virtual Project Project { get; set; }
        public virtual Scope Scope { get; set; }
        public virtual ScopeOfWork ScopeOfWork { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StatusLog> StatusLogs { get; set; }
    }
}
