//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LNTSlipPortal_Repository.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ScopeOfWork
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ScopeOfWork()
        {
            this.RAWS = new HashSet<RAW>();
        }
    
        public int ScopeOfWorkId { get; set; }
        public Nullable<bool> Grinding { get; set; }
        public Nullable<bool> PaintTouchUp { get; set; }
        public Nullable<bool> Replacement { get; set; }
        public Nullable<bool> Testing { get; set; }
        public Nullable<bool> Assembly { get; set; }
        public string Other { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RAW> RAWS { get; set; }
    }
}
