//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LNTSlipPortal_Repository.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class StatusLog
    {
        public int StatusLogId { get; set; }
        public int StatusId { get; set; }
        public int UserId { get; set; }
        public int RAWSID { get; set; }
        public System.DateTime CreatedAt { get; set; }
    
        public virtual RAW RAW { get; set; }
        public virtual Status Status { get; set; }
        public virtual UserMaster UserMaster { get; set; }
    }
}
